### ISSUE TITLE
Error with custom test runners.

### ISSUE THREAD

**Issue by kevincox** [alopatindev/cargo-limit#4]
```toml
# Cargo.toml
[[test]]
name = "solutions"
harness = false
```

```
Testing "tests/solutions/--color=always"
Error testing "tests/solutions/--color=always"
```

You can see an example here: https://gitlab.com/kevincox/ricochetrobots. `cargo test` works but `cargo ltest` doesn't. I am using version 0.0.7.
